site_name: Basics of Git
# repo_url: https://github.com/Jacopo-DM/GitTutorial
theme:
  favicon: assets/fav.svg
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.indexes
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Welcome: 
    - 'index.md'
    - About The Presenter: 'welcome/about_me.md'
    - Cheatsheet: 'welcome/cheatsheet.md'
  - Getting Started:
    - 'get_started/index.md'
    - 'Part 1: Installing Git': 'get_started/stage_1.md'
    - 'Part 2: Setting Up GitHub': 'get_started/stage_2.md'
    - 'Part 3: Our First Repo': 'get_started/stage_3.md'
    - 'Part 4: Cloning The Repository': 'get_started/stage_4.md'
    - 'Part 5: Our First Commit': 'get_started/stage_5.md'
    - 'Part 6: Deleting & Ignoring': 'get_started/stage_6.md'
    - 'Part 7: Remote Changes': 'get_started/stage_7.md'
  - Project:
    - 'project/index.md'
    - MNIST Classifier:
      - 'project/mnist/index.md'
    - Minecraft Clone:
      - 'project/minecraft/index.md'
    - Personal Website:
      - 'project/website/index.md'



markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3


  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.critic

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
